spring:
  application:
    name: server
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/pulsepad}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${PORT:8080}